[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["node"]

[deploy]
preDeployCommand = "npx prisma db push --accept-data-loss --skip-generate"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
